"""rename workflow__conversation_variables to workflow_conversation_variables

Revision ID: 2dbe42621d96
Revises: a6be81136580
Create Date: 2024-08-20 04:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = '2dbe42621d96'
down_revision = 'a6be81136580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    old_table = 'workflow__conversation_variables'
    new_table = 'workflow_conversation_variables'

    if _is_pg(conn):
        # PostgreSQL 保留原有语法
        op.rename_table(old_table, new_table)
    else:
        # MySQL 使用原生 RENAME TABLE 语法
        op.execute(f"RENAME TABLE {old_table} TO {new_table};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    old_table = 'workflow__conversation_variables'
    new_table = 'workflow_conversation_variables'

    if _is_pg(conn):
        # PostgreSQL 回滚
        op.rename_table(new_table, old_table)
    else:
        # MySQL 回滚
        op.execute(f"RENAME TABLE {new_table} TO {old_table};")
    # ### end Alembic commands ###
