"""add-tidb-auth-binding

Revision ID: 0251a1c768cc
Revises: bbadea11becb
Create Date: 2024-08-15 09:56:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0251a1c768cc'
down_revision = 'bbadea11becb'
branch_labels = None
depends_on = None

def _is_pg(conn):
    """判断是否为PostgreSQL数据库"""
    return conn.dialect.name == "postgresql"

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    if is_postgresql:
        # PostgreSQL 保留原有 ORM 写法
        op.create_table('tidb_auth_bindings',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('tenant_id', sa.CHAR(36), nullable=True),
        sa.Column('cluster_id', sa.VARCHAR(255), nullable=False),
        sa.Column('cluster_name', sa.VARCHAR(255), nullable=False),
        sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('status', sa.VARCHAR(255), server_default=sa.text("'CREATING'"), nullable=False),
        sa.Column('account', sa.VARCHAR(255), nullable=False),
        sa.Column('password', sa.VARCHAR(255), nullable=False),
        sa.Column('created_at', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='tidb_auth_bindings_pkey')
        )
    else:
        # MySQL 使用原生 SQL 创建表（替换 BOOL 为 BOOLEAN，保留 DEFAULT false）
        op.execute("""
            CREATE TABLE tidb_auth_bindings (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NULL,
                cluster_id VARCHAR(255) NOT NULL,
                cluster_name VARCHAR(255) NOT NULL,
                active BOOLEAN NOT NULL DEFAULT false,
                status VARCHAR(255) NOT NULL DEFAULT 'CREATING',
                account VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tidb_auth_bindings')
    # ### end Alembic commands ###
