"""add use_icon_as_answer_icon fields for app and site

Revision ID: 030f4915f36a
Revises: d0187d6a88dd
Create Date: 2024-09-01 12:55:45.129687

"""

import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = "030f4915f36a"
down_revision = "d0187d6a88dd"
branch_labels = None
depends_on = None


def _is_pg(conn):
    """判断是否为PostgreSQL数据库"""
    return conn.dialect.name == "postgresql"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    if is_postgresql:
        # PostgreSQL 保留原有 ORM 写法
        with op.batch_alter_table("apps", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("use_icon_as_answer_icon", sa.Boolean(), server_default=sa.text("false"), nullable=False)
            )
        with op.batch_alter_table("sites", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("use_icon_as_answer_icon", sa.Boolean(), server_default=sa.text("false"), nullable=False)
            )
    else:
        # MySQL 使用原生 SQL 执行（显式指定 BOOLEAN + DEFAULT false）
        # 核心：MySQL 原生支持 BOOLEAN 类型（底层是 TINYINT(1)），且支持 DEFAULT false
        op.execute("""
            ALTER TABLE apps
            ADD COLUMN use_icon_as_answer_icon BOOLEAN NOT NULL DEFAULT false;
        """)
        op.execute("""
            ALTER TABLE sites
            ADD COLUMN use_icon_as_answer_icon BOOLEAN NOT NULL DEFAULT false;
        """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    if is_postgresql:
        with op.batch_alter_table("sites", schema=None) as batch_op:
            batch_op.drop_column("use_icon_as_answer_icon")
        with op.batch_alter_table("apps", schema=None) as batch_op:
            batch_op.drop_column("use_icon_as_answer_icon")
    else:
        op.execute("ALTER TABLE sites DROP COLUMN use_icon_as_answer_icon;")
        op.execute("ALTER TABLE apps DROP COLUMN use_icon_as_answer_icon;")
    # ### end Alembic commands ###
