"""add WorkflowDraftVariable model

Revision ID: 2adcbe1f5dfb
Revises: d28f2004b072
Create Date: 2025-05-15 15:31:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2adcbe1f5dfb'
down_revision = 'd28f2004b072'
branch_labels = None
depends_on = None

def _is_pg(conn):
    return conn.dialect.name == "postgresql"

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    if is_postgresql:
        op.create_table(
            'workflow_draft_variables',
            sa.Column('id', sa.CHAR(36), nullable=False),
            sa.Column('created_at', sa.DATETIME(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('updated_at', sa.DATETIME(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('app_id', sa.CHAR(36), nullable=False),
            sa.Column('last_edited_at', sa.DATETIME(), nullable=True),
            sa.Column('node_id', sa.VARCHAR(255), nullable=False),
            sa.Column('name', sa.VARCHAR(255), nullable=False),
            sa.Column('description', sa.VARCHAR(255), nullable=False),
            sa.Column('selector', sa.VARCHAR(255), nullable=False),
            sa.Column('value_type', sa.VARCHAR(20), nullable=False),
            sa.Column('value', sa.LONGTEXT(), nullable=False),
            sa.Column('visible', sa.Boolean(), nullable=False),
            sa.Column('editable', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('app_id', 'node_id', 'name', name='workflow_draft_variables_app_id_key')
        )
    else:
        op.execute("""
            CREATE TABLE workflow_draft_variables (
                id CHAR(36) NOT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                app_id CHAR(36) NOT NULL,
                last_edited_at DATETIME NULL,
                node_id VARCHAR(255) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description VARCHAR(255) NOT NULL,
                selector VARCHAR(255) NOT NULL,
                value_type VARCHAR(20) NOT NULL,
                value LONGTEXT NOT NULL,
                `visible` BOOLEAN NOT NULL,
                editable BOOLEAN NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY workflow_draft_variables_app_id_key (app_id, node_id, name)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_draft_variables')
    # ### end Alembic commands ###
