"""add_metadata_function

Revision ID: d20049ed0af6
Revises: f051706725cc
Create Date: 2025-02-27 09:17:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd20049ed0af6'
down_revision = 'f051706725cc'
branch_labels = None
depends_on = None

def _is_pg(conn):
    """判断是否为PostgreSQL数据库"""
    return conn.dialect.name == "postgresql"

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    # 处理 datasets 表添加字段
    if is_postgresql:
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('built_in_field_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
            batch_op.add_column(sa.Column('metadata_extraction_function', sa.Text(), nullable=True))
    else:
        # MySQL 使用原生 SQL 添加字段（替换 BOOL 为 BOOLEAN，保留 DEFAULT false）
        op.execute("ALTER TABLE datasets ADD COLUMN built_in_field_enabled BOOLEAN NOT NULL DEFAULT false;")
        op.execute("ALTER TABLE datasets ADD COLUMN metadata_extraction_function TEXT NULL;")

    # 处理 documents 表添加字段
    if is_postgresql:
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.add_column(sa.Column('metadata_extraction_function', sa.Text(), nullable=True))
    else:
        op.execute("ALTER TABLE documents ADD COLUMN metadata_extraction_function TEXT NULL;")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    # 回滚 documents 表字段
    if is_postgresql:
        with op.batch_alter_table('documents', schema=None) as batch_op:
            batch_op.drop_column('metadata_extraction_function')
    else:
        op.execute("ALTER TABLE documents DROP COLUMN metadata_extraction_function;")

    # 回滚 datasets 表字段
    if is_postgresql:
        with op.batch_alter_table('datasets', schema=None) as batch_op:
            batch_op.drop_column('metadata_extraction_function')
            batch_op.drop_column('built_in_field_enabled')
    else:
        op.execute("ALTER TABLE datasets DROP COLUMN metadata_extraction_function;")
        op.execute("ALTER TABLE datasets DROP COLUMN built_in_field_enabled;")
    # ### end Alembic commands ###
