"""add mcp server tool and app server

Revision ID: 58eb7bdb93fe
Revises: 0ab65e1cc7fa
Create Date: 2025-06-25 09:36:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '58eb7bdb93fe'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None

def _is_pg(conn):
    return conn.dialect.name == "postgresql"

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    # 1. 创建 app_mcp_servers 表
    if is_postgresql:
        op.create_table('app_mcp_servers',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('tenant_id', sa.CHAR(36), nullable=False),
        sa.Column('app_id', sa.CHAR(36), nullable=False),
        sa.Column('name', sa.VARCHAR(255), nullable=False),
        sa.Column('description', sa.VARCHAR(255), nullable=False),
        sa.Column('server_code', sa.VARCHAR(255), nullable=False),
        sa.Column('status', sa.VARCHAR(255), server_default=sa.text("'normal'"), nullable=False),
        sa.Column('parameters', sa.LONGTEXT(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='app_mcp_server_pkey'),
        sa.UniqueConstraint('tenant_id', 'app_id', name='unique_app_mcp_server_tenant_app_id'),
        sa.UniqueConstraint('server_code', name='unique_app_mcp_server_server_code')
        )
    else:
        # MySQL 原生 SQL：parameters 加反引号转义（保留关键字）
        op.execute("""
            CREATE TABLE app_mcp_servers (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                app_id CHAR(36) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description VARCHAR(255) NOT NULL,
                server_code VARCHAR(255) NOT NULL,
                status VARCHAR(255) NOT NULL DEFAULT 'normal',
                `parameters` TEXT NOT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY unique_app_mcp_server_tenant_app_id (tenant_id, app_id),
                UNIQUE KEY unique_app_mcp_server_server_code (server_code)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)

    # 2. 创建 tool_mcp_servers 表（若原文件包含此逻辑，同步适配）
    if is_postgresql:
        op.create_table('tool_mcp_servers',
        sa.Column('id', sa.CHAR(36), nullable=False),
        sa.Column('tenant_id', sa.CHAR(36), nullable=False),
        sa.Column('tool_id', sa.CHAR(36), nullable=False),
        sa.Column('name', sa.VARCHAR(255), nullable=False),
        sa.Column('description', sa.VARCHAR(255), nullable=False),
        sa.Column('server_code', sa.VARCHAR(255), nullable=False),
        sa.Column('status', sa.VARCHAR(255), server_default=sa.text("'normal'"), nullable=False),
        sa.Column('parameters', sa.LONGTEXT(), nullable=False),
        sa.Column('created_at', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='tool_mcp_server_pkey'),
        sa.UniqueConstraint('tenant_id', 'tool_id', name='unique_tool_mcp_server_tenant_tool_id'),
        sa.UniqueConstraint('server_code', name='unique_tool_mcp_server_server_code')
        )
    else:
        op.execute("""
            CREATE TABLE tool_mcp_servers (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                tool_id CHAR(36) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description VARCHAR(255) NOT NULL,
                server_code VARCHAR(255) NOT NULL,
                status VARCHAR(255) NOT NULL DEFAULT 'normal',
                `parameters` TEXT NOT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY unique_tool_mcp_server_tenant_tool_id (tenant_id, tool_id),
                UNIQUE KEY unique_tool_mcp_server_server_code (server_code)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_mcp_servers')
    op.drop_table('app_mcp_servers')
    # ### end Alembic commands ###
