"""tool oauth

Revision ID: 71f5020c6470
Revises: 4474872b0ee6
Create Date: 2025-06-24 17:05:43.118647

"""
from alembic import op
import models as models
import sqlalchemy as sa


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = '71f5020c6470'
down_revision = '1c9ba48be8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    # 1. 创建 tool_oauth_system_clients 表
    if is_postgresql:
        op.create_table('tool_oauth_system_clients',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('plugin_id', sa.String(length=512), nullable=False),
        sa.Column('provider', sa.String(length=255), nullable=False),
        sa.Column('encrypted_oauth_params', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name='tool_oauth_system_client_pkey'),
        sa.UniqueConstraint('plugin_id', 'provider', name='tool_oauth_system_client_plugin_id_provider_idx')
        )
    else:
        # MySQL 完全原生SQL
        op.execute("""
            CREATE TABLE tool_oauth_system_clients (
                id CHAR(36) NOT NULL,
                plugin_id VARCHAR(512) NOT NULL,
                provider VARCHAR(255) NOT NULL,
                encrypted_oauth_params TEXT NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY tool_oauth_system_client_plugin_id_provider_idx (plugin_id, provider)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)

    # 2. 创建 tool_oauth_tenant_clients 表
    if is_postgresql:
        op.create_table('tool_oauth_tenant_clients',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
        sa.Column('plugin_id', sa.String(length=512), nullable=False),
        sa.Column('provider', sa.String(length=255), nullable=False),
        sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('encrypted_oauth_params', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name='tool_oauth_tenant_client_pkey'),
        sa.UniqueConstraint('tenant_id', 'plugin_id', 'provider', name='unique_tool_oauth_tenant_client')
        )
    else:
        # MySQL 完全原生SQL
        op.execute("""
            CREATE TABLE tool_oauth_tenant_clients (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                plugin_id VARCHAR(255) NOT NULL,
                provider VARCHAR(255) NOT NULL,
                enabled TINYINT(1) NOT NULL DEFAULT 1,
                encrypted_oauth_params TEXT NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY unique_tool_oauth_tenant_client (tenant_id, plugin_id, provider)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)

    # 3. 修改 tool_builtin_providers 表
    if is_postgresql:
        with op.batch_alter_table('tool_builtin_providers', schema=None) as batch_op:
            batch_op.add_column(sa.Column('name', sa.String(length=256), server_default=sa.text("'API KEY 1'::character varying"), nullable=False))
            batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
            batch_op.add_column(sa.Column('credential_type', sa.String(length=32), server_default=sa.text("'api-key'::character varying"), nullable=False))
            batch_op.drop_constraint(batch_op.f('unique_builtin_tool_provider'), type_='unique')
            batch_op.create_unique_constraint(batch_op.f('unique_builtin_tool_provider'), ['tenant_id', 'provider', 'name'])
    else:
        # MySQL 完全原生SQL（分步骤执行）
        # 添加字段
        op.execute("ALTER TABLE tool_builtin_providers ADD COLUMN name VARCHAR(256) NOT NULL DEFAULT 'API KEY 1';")
        op.execute("ALTER TABLE tool_builtin_providers ADD COLUMN is_default TINYINT(1) NOT NULL DEFAULT 0;")
        op.execute("ALTER TABLE tool_builtin_providers ADD COLUMN credential_type VARCHAR(32) NOT NULL DEFAULT 'api-key';")
        # 删除旧唯一约束
        op.execute("ALTER TABLE tool_builtin_providers DROP INDEX unique_builtin_tool_provider;")
        # 创建新唯一约束
        op.execute("ALTER TABLE tool_builtin_providers ADD UNIQUE KEY unique_builtin_tool_provider (tenant_id, provider, name);")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_postgresql = _is_pg(conn)

    # 回滚 tool_builtin_providers 表
    if is_postgresql:
        with op.batch_alter_table('tool_builtin_providers', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('unique_builtin_tool_provider'), type_='unique')
            batch_op.create_unique_constraint(batch_op.f('unique_builtin_tool_provider'), ['tenant_id', 'provider'])
            batch_op.drop_column('credential_type')
            batch_op.drop_column('is_default')
            batch_op.drop_column('name')
    else:
        # MySQL 完全原生SQL回滚
        # 删除新唯一约束
        op.execute("ALTER TABLE tool_builtin_providers DROP INDEX unique_builtin_tool_provider;")
        # 重建旧唯一约束
        op.execute("ALTER TABLE tool_builtin_providers ADD UNIQUE KEY unique_builtin_tool_provider (tenant_id, provider);")
        # 删除新增字段
        op.execute("ALTER TABLE tool_builtin_providers DROP COLUMN credential_type;")
        op.execute("ALTER TABLE tool_builtin_providers DROP COLUMN is_default;")
        op.execute("ALTER TABLE tool_builtin_providers DROP COLUMN name;")

    # 回滚删除表
    if is_postgresql:
        op.drop_table('tool_oauth_tenant_clients')
        op.drop_table('tool_oauth_system_clients')
    else:
        op.execute("DROP TABLE IF EXISTS tool_oauth_tenant_clients;")
        op.execute("DROP TABLE IF EXISTS tool_oauth_system_clients;")
    # ### end Alembic commands ###
