"""empty message

Revision ID: 8d289573e1da
Revises: 0e154742a5fa
Create Date: 2025-08-20 17:47:17.015695

"""
from alembic import op
import models as models
import sqlalchemy as sa


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = '8d289573e1da'
down_revision = '0e154742a5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        # PG 部分逻辑保持不变
        op.create_table('oauth_provider_apps',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuidv7()'), nullable=False),
        sa.Column('app_icon', sa.String(length=255), nullable=False),
        sa.Column('app_label', sa.JSON(), server_default='{}', nullable=False),
        sa.Column('client_id', sa.String(length=255), nullable=False),
        sa.Column('client_secret', sa.String(length=255), nullable=False),
        sa.Column('redirect_uris', sa.JSON(), server_default='[]', nullable=False),
        sa.Column('scope', sa.String(length=255), server_default=sa.text("'read:name read:email read:avatar read:interface_language read:timezone'"),nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),nullable=False),
        sa.PrimaryKeyConstraint('id', name='oauth_provider_app_pkey')
        )
    else:
        # MySQL 部分改用原生 SQL 执行
        # 核心修复：1. scope 加反引号转义 2. JSON 类型适配 MySQL 3. 默认值格式适配
        op.execute("""
        CREATE TABLE oauth_provider_apps (
            id CHAR(36) NOT NULL,
            app_icon VARCHAR(255) NOT NULL,
            app_label JSON NOT NULL DEFAULT '{}',
            client_id VARCHAR(255) NOT NULL,
            client_secret VARCHAR(255) NOT NULL,
            redirect_uris JSON NOT NULL DEFAULT '[]',
            `scope` VARCHAR(255) NOT NULL DEFAULT 'read:name read:email read:avatar read:interface_language read:timezone',
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)
        # 创建索引（原生 SQL 方式）
        op.execute("""
        CREATE INDEX oauth_provider_app_client_id_idx ON oauth_provider_apps (client_id);
        """)

    # 移除原有的 batch_alter_table 逻辑（已在 MySQL 分支用原生 SQL 创建索引）
    if _is_pg(conn):
        with op.batch_alter_table('oauth_provider_apps', schema=None) as batch_op:
            batch_op.create_index('oauth_provider_app_client_id_idx', ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 统一删除表（原生 DROP TABLE 兼容所有数据库）
    op.execute("DROP TABLE IF EXISTS oauth_provider_apps;")
    # ### end Alembic commands ###
