"""add load balancing

Revision ID: 4e99a8df00ff
Revises: 47cc7df8c4f3
Create Date: 2024-05-10 12:08:09.812736

"""
import sqlalchemy as sa
from alembic import op

import models.types


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = '4e99a8df00ff'
down_revision = '64a70a7aab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        op.create_table('load_balancing_model_configs',
                        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'),
                                  nullable=False),
                        sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
                        sa.Column('provider_name', sa.String(length=255), nullable=False),
                        sa.Column('model_name', sa.String(length=255), nullable=False),
                        sa.Column('model_type', sa.String(length=40), nullable=False),
                        sa.Column('name', sa.String(length=255), nullable=False),
                        sa.Column('encrypted_config', sa.Text(), nullable=True),
                        sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                                  nullable=False),
                        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                                  nullable=False),
                        sa.PrimaryKeyConstraint('id', name='load_balancing_model_config_pkey')
                        )
    else:
        # 核心修改：Dingodb 不支持 boolean，替换为 TINYINT(1)，默认值 1/0 替代 true/false
        conn.execute(sa.text("""
            CREATE TABLE load_balancing_model_configs (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                provider_name VARCHAR(255) NOT NULL,
                model_name VARCHAR(255) NOT NULL,
                model_type VARCHAR(40) NOT NULL,
                name VARCHAR(255) NOT NULL,
                encrypted_config LONGTEXT,
                enabled boolean NOT NULL DEFAULT true,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            )
        """))

    # 保留 batch_alter_table 创建索引（若仍报错可替换为原生 SQL）
    with op.batch_alter_table('load_balancing_model_configs', schema=None) as batch_op:
        batch_op.create_index('load_balancing_model_config_tenant_provider_model_idx',
                              ['tenant_id', 'provider_name', 'model_type'],
                              unique=False)

    if _is_pg(conn):
        op.create_table('provider_model_settings',
                        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'),
                                  nullable=False),
                        sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
                        sa.Column('provider_name', sa.String(length=255), nullable=False),
                        sa.Column('model_name', sa.String(length=255), nullable=False),
                        sa.Column('model_type', sa.String(length=40), nullable=False),
                        sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                        sa.Column('load_balancing_enabled', sa.Boolean(), server_default=sa.text('false'),
                                  nullable=False),
                        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                                  nullable=False),
                        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                                  nullable=False),
                        sa.PrimaryKeyConstraint('id', name='provider_model_setting_pkey')
                        )
    else:
        # 核心修改：Dingodb 兼容，boolean → TINYINT(1)，true=1/false=0
        conn.execute(sa.text("""
            CREATE TABLE provider_model_settings (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                provider_name VARCHAR(255) NOT NULL,
                model_name VARCHAR(255) NOT NULL,
                model_type VARCHAR(40) NOT NULL,
                enabled boolean NOT NULL DEFAULT true,
                load_balancing_enabled TINYINT(1) NOT NULL DEFAULT 0,  -- 0=false
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            )
        """))

    # 保留 batch_alter_table 创建索引
    with op.batch_alter_table('provider_model_settings', schema=None) as batch_op:
        batch_op.create_index('provider_model_setting_tenant_provider_model_idx',
                              ['tenant_id', 'provider_name', 'model_type'],
                              unique=False)

    # 修改字段长度：改用原生 SQL 避免 batch_alter_table 兼容问题
    alter_sqls = [
        "ALTER TABLE provider_models MODIFY provider_name VARCHAR(255) NOT NULL;",
        "ALTER TABLE provider_orders MODIFY provider_name VARCHAR(255) NOT NULL;",
        "ALTER TABLE providers MODIFY provider_name VARCHAR(255) NOT NULL;",
        "ALTER TABLE tenant_default_models MODIFY provider_name VARCHAR(255) NOT NULL;",
        "ALTER TABLE tenant_preferred_model_providers MODIFY provider_name VARCHAR(255) NOT NULL;"
    ]
    for sql in alter_sqls:
        conn.execute(sa.text(sql))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚字段长度修改
    rollback_sqls = [
        "ALTER TABLE tenant_preferred_model_providers MODIFY provider_name VARCHAR(40) NOT NULL;",
        "ALTER TABLE tenant_default_models MODIFY provider_name VARCHAR(40) NOT NULL;",
        "ALTER TABLE providers MODIFY provider_name VARCHAR(40) NOT NULL;",
        "ALTER TABLE provider_orders MODIFY provider_name VARCHAR(40) NOT NULL;",
        "ALTER TABLE provider_models MODIFY provider_name VARCHAR(40) NOT NULL;"
    ]
    conn = op.get_bind()
    for sql in rollback_sqls:
        conn.execute(sa.text(sql))

    # 回滚索引和表
    with op.batch_alter_table('provider_model_settings', schema=None) as batch_op:
        batch_op.drop_index('provider_model_setting_tenant_provider_model_idx')
    op.drop_table('provider_model_settings')

    with op.batch_alter_table('load_balancing_model_configs', schema=None) as batch_op:
        batch_op.drop_index('load_balancing_model_config_tenant_provider_model_idx')
    op.drop_table('load_balancing_model_configs')
    # ### end Alembic commands ###
