"""add workflow to site

Revision ID: 4ff534e1eb11
Revises: 7b45942e39bb
Create Date: 2024-06-21 04:16:03.419634

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '4ff534e1eb11'
down_revision = '7b45942e39bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 核心修复：改用原生 SQL 指定 Dingodb 支持的 BOOLEAN 全称类型
    # 替代 SQLAlchemy 自动生成的 BOOL 缩写（Dingodb 不识别）
    conn = op.get_bind()
    # 使用 BOOLEAN 全称 + DEFAULT true（Dingodb 支持该写法）
    conn.execute(sa.text("""
        ALTER TABLE sites
        ADD COLUMN show_workflow_steps BOOLEAN NOT NULL DEFAULT true;
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 改用原生 SQL 删除字段，避免 batch_alter_table 兼容问题
    conn = op.get_bind()
    conn.execute(sa.text("ALTER TABLE sites DROP COLUMN show_workflow_steps;"))
    # ### end Alembic commands ###
