"""add-api-key-auth-binding

Revision ID: 7b45942e39bb
Revises: 47cc7df8c4f3
Create Date: 2024-05-14 07:31:29.702766

"""
import sqlalchemy as sa
from alembic import op

import models.types


def _is_pg(conn):
    return conn.dialect.name == "postgresql"

# revision identifiers, used by Alembic.
revision = '7b45942e39bb'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        # PostgreSQL: Keep original syntax
        op.create_table('data_source_api_key_auth_bindings',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'),
                  nullable=False),
        sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
        sa.Column('category', sa.String(length=255), nullable=False),
        sa.Column('provider', sa.String(length=255), nullable=False),
        sa.Column('credentials', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                  nullable=False),
        sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.PrimaryKeyConstraint('id', name='data_source_api_key_auth_binding_pkey')
        )
    else:
        # 保留 Dingodb 支持的 boolean 类型写法
        conn.execute(sa.text("""
            CREATE TABLE data_source_api_key_auth_bindings (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                category VARCHAR(255) NOT NULL,
                provider VARCHAR(255) NOT NULL,
                credentials LONGTEXT,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                disabled boolean DEFAULT false,  -- Dingodb 支持该写法，无需修改
                PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;  -- 补充引擎和字符集，增强兼容性
        """))

    # 创建索引：区分 PG/MySQL 语法，解决 IF NOT EXISTS 兼容问题
    if _is_pg(conn):
        # PG 保留 IF NOT EXISTS 语法
        op.execute("""
        CREATE INDEX IF NOT EXISTS data_source_api_key_auth_binding_provider_idx
        ON data_source_api_key_auth_bindings (provider);
        """)
        op.execute("""
        CREATE INDEX IF NOT EXISTS data_source_api_key_auth_binding_tenant_id_idx
        ON data_source_api_key_auth_bindings (tenant_id);
        """)
    else:
        # MySQL 适配：先判断索引是否存在，不存在再创建（兼容低版本 MySQL）
        # 创建 provider 索引
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_api_key_auth_bindings'
          AND index_name = 'data_source_api_key_auth_binding_provider_idx';

        IF @index_exists = 0 THEN
            CREATE INDEX data_source_api_key_auth_binding_provider_idx
            ON data_source_api_key_auth_bindings (provider);
        END IF;
        """)
        # 创建 tenant_id 索引
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_api_key_auth_bindings'
          AND index_name = 'data_source_api_key_auth_binding_tenant_id_idx';

        IF @index_exists = 0 THEN
            CREATE INDEX data_source_api_key_auth_binding_tenant_id_idx
            ON data_source_api_key_auth_bindings (tenant_id);
        END IF;
        """)

    if not _is_pg(conn):
        pass

    # 表重命名改用 Dingodb 支持的 RENAME TABLE 语法
    op.execute(sa.text("RENAME TABLE data_source_bindings TO data_source_oauth_bindings;"))

    # 重建新表索引：区分 PG/MySQL 语法
    if _is_pg(conn):
        op.execute("""
        CREATE INDEX IF NOT EXISTS source_binding_tenant_id_idx
        ON data_source_oauth_bindings (tenant_id);
        """)
    else:
        # MySQL 适配：先判断索引是否存在，不存在再创建
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_oauth_bindings'
          AND index_name = 'source_binding_tenant_id_idx';

        IF @index_exists = 0 THEN
            CREATE INDEX source_binding_tenant_id_idx
            ON data_source_oauth_bindings (tenant_id);
        END IF;
        """)

    if _is_pg(conn):
        op.execute("""
        CREATE INDEX IF NOT EXISTS source_info_idx
        ON data_source_oauth_bindings USING gin (source_info);
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # 回滚：删除索引（区分 PG/MySQL，加容错逻辑）
    if _is_pg(conn):
        try:
            op.execute("DROP INDEX IF EXISTS source_binding_tenant_id_idx ON data_source_oauth_bindings;")
        except:
            pass
        try:
            op.execute("DROP INDEX IF EXISTS source_info_idx ON data_source_oauth_bindings USING gin;")
        except:
            pass
    else:
        # MySQL 先判断索引存在再删除
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_oauth_bindings'
          AND index_name = 'source_binding_tenant_id_idx';

        IF @index_exists = 1 THEN
            DROP INDEX source_binding_tenant_id_idx ON data_source_oauth_bindings;
        END IF;
        """)

    # 核心回滚：表重命名
    op.execute(sa.text("RENAME TABLE data_source_oauth_bindings TO data_source_bindings;"))

    # 回滚：重建索引（区分 PG/MySQL 语法）
    if _is_pg(conn):
        op.execute("""
        CREATE INDEX IF NOT EXISTS source_binding_tenant_id_idx
        ON data_source_bindings (tenant_id);
        """)
        op.execute("""
        CREATE INDEX IF NOT EXISTS source_info_idx
        ON data_source_bindings USING gin (source_info);
        """)
    else:
        # MySQL 先判断索引是否存在，不存在再创建
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_bindings'
          AND index_name = 'source_binding_tenant_id_idx';

        IF @index_exists = 0 THEN
            CREATE INDEX source_binding_tenant_id_idx
            ON data_source_bindings (tenant_id);
        END IF;
        """)

    # 回滚：删除 api key 相关索引（区分 PG/MySQL，加容错）
    if _is_pg(conn):
        try:
            op.execute(
                "DROP INDEX IF EXISTS data_source_api_key_auth_binding_tenant_id_idx ON data_source_api_key_auth_bindings;")
            op.execute(
                "DROP INDEX IF EXISTS data_source_api_key_auth_binding_provider_idx ON data_source_api_key_auth_bindings;")
        except:
            pass
    else:
        # MySQL 先判断索引存在再删除
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_api_key_auth_bindings'
          AND index_name = 'data_source_api_key_auth_binding_tenant_id_idx';

        IF @index_exists = 1 THEN
            DROP INDEX data_source_api_key_auth_binding_tenant_id_idx ON data_source_api_key_auth_bindings;
        END IF;
        """)
        op.execute("""
        SET @index_exists = 0;
        SELECT COUNT(*) INTO @index_exists
        FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_schema = DATABASE()
          AND table_name = 'data_source_api_key_auth_bindings'
          AND index_name = 'data_source_api_key_auth_binding_provider_idx';

        IF @index_exists = 1 THEN
            DROP INDEX data_source_api_key_auth_binding_provider_idx ON data_source_api_key_auth_bindings;
        END IF;
        """)

    op.drop_table('data_source_api_key_auth_bindings')
    # ### end Alembic commands ###
