"""add tool providers

Revision ID: 7ce5a52e4eee
Revises: 2beac44e5f5f
Create Date: 2023-07-10 10:26:50.074515

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import models.types


def _is_pg(conn):
    return conn.dialect.name == "postgresql"

# revision identifiers, used by Alembic.
revision = '7ce5a52e4eee'
down_revision = '2beac44e5f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        op.create_table('tool_providers',
        sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(), nullable=False),
        sa.Column('tool_name', sa.String(length=40), nullable=False),
        sa.Column('encrypted_credentials', sa.Text(), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='tool_provider_pkey'),
        sa.UniqueConstraint('tenant_id', 'tool_name', name='unique_tool_provider_tool_name')
        )
    else:
        conn.execute(sa.text("""
            CREATE TABLE tool_providers (
                id CHAR(36) NOT NULL,
                tenant_id CHAR(36) NOT NULL,
                tool_name VARCHAR(40) NOT NULL,
                encrypted_credentials LONGTEXT,
                is_enabled boolean NOT NULL DEFAULT false,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT tool_provider_pkey PRIMARY KEY (id),
                CONSTRAINT unique_tool_provider_tool_name UNIQUE (tenant_id, tool_name)
            )
        """))

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensitive_word_avoidance', models.types.LongText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('sensitive_word_avoidance')

    op.drop_table('tool_providers')
    # ### end Alembic commands ###
