"""add language to recommend apps

Revision ID: a45f4dfde53b
Revises: 9f4e3427ea84
Create Date: 2023-05-25 17:50:32.052335

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import quoted_name


def _is_pg(conn):
    return conn.dialect.name == "postgresql"

# revision identifiers, used by Alembic.
revision = 'a45f4dfde53b'
down_revision = '9f4e3427ea84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        with op.batch_alter_table('recommended_apps', schema=None) as batch_op:
            batch_op.add_column(sa.Column('language', sa.String(length=255), server_default=sa.text("'en-US'::character varying"), nullable=False))
            batch_op.drop_index('recommended_app_is_listed_idx')
            batch_op.create_index('recommended_app_is_listed_idx', ['is_listed', 'language'], unique=False)
    else:
        with op.batch_alter_table('recommended_apps', schema=None) as batch_op:
            conn.execute(sa.text("ALTER TABLE recommended_apps ADD COLUMN `language` VARCHAR(255) NOT NULL DEFAULT 'en-US'"))
            conn.execute(sa.text("DROP INDEX IF EXISTS recommended_app_is_listed_idx ON recommended_apps"))
            conn.execute(sa.text("CREATE INDEX recommended_app_is_listed_idx ON recommended_apps (is_listed, `language`)"))

            # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_apps', schema=None) as batch_op:
        batch_op.drop_index('recommended_app_is_listed_idx')
        batch_op.create_index('recommended_app_is_listed_idx', ['is_listed'], unique=False)
        batch_op.drop_column('language')

    # ### end Alembic commands ###
