"""remove app model config trace config and rename trace app config

Revision ID: c031d46af369
Revises: 04c602f5dc9b
Create Date: 2024-06-17 10:01:00.255189

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import models.types


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = 'c031d46af369'
down_revision = '04c602f5dc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        # PostgreSQL 保持原有 ORM 方式创建表
        op.create_table('trace_app_config',
                        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'),
                                  nullable=False),
                        sa.Column('app_id', models.types.StringUUID(), nullable=False),
                        sa.Column('tracing_provider', sa.String(length=255), nullable=True),
                        sa.Column('tracing_config', sa.JSON(), nullable=True),
                        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
                        sa.PrimaryKeyConstraint('id', name='trace_app_config_pkey')
                        )
    else:
        # MySQL 使用原生 SQL 创建表（兼容布尔类型为 TINYINT(1)）
        op.execute("""
            CREATE TABLE trace_app_config (
                id VARCHAR(36) NOT NULL PRIMARY KEY,
                app_id VARCHAR(36) NOT NULL,
                tracing_provider VARCHAR(255) NULL,
                tracing_config JSON NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                is_active BOOLEAN NOT NULL DEFAULT false,
                CONSTRAINT trace_app_config_pkey PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """)

    # 统一创建索引（兼容 PostgreSQL/MySQL）
    with op.batch_alter_table('trace_app_config', schema=None) as batch_op:
        batch_op.create_index('trace_app_config_app_id_idx', ['app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_app_config')
    # ### end Alembic commands ###
