"""set model config column nullable

Revision ID: cc04d0998d4d
Revises: b289e2408ee2
Create Date: 2024-02-27 03:47:47.376325

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy import text


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


# revision identifiers, used by Alembic.
revision = 'cc04d0998d4d'
down_revision = 'b289e2408ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    if _is_pg(conn):
        with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
            batch_op.alter_column('provider',
                                  existing_type=sa.VARCHAR(length=255),
                                  nullable=True)
            batch_op.alter_column('model_id',
                                  existing_type=sa.VARCHAR(length=255),
                                  nullable=True)
            batch_op.alter_column('configs',
                                  existing_type=postgresql.JSON(astext_type=sa.Text()),
                                  nullable=True)
    else:
        op.execute("ALTER TABLE app_model_configs MODIFY provider VARCHAR(255) NULL;")
        op.execute("ALTER TABLE app_model_configs MODIFY model_id VARCHAR(255) NULL;")
        op.execute("ALTER TABLE app_model_configs MODIFY configs JSON NULL;")
        op.execute("ALTER TABLE apps MODIFY api_rpm INTEGER NOT NULL DEFAULT 0;")
        op.execute("ALTER TABLE apps MODIFY api_rph INTEGER NOT NULL DEFAULT 0;")
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.execute("ALTER TABLE apps MODIFY api_rpm INTEGER NOT NULL;")
    op.execute("ALTER TABLE apps MODIFY api_rph INTEGER NOT NULL;")

    if _is_pg(conn):
        with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
            batch_op.alter_column('configs',
                                  existing_type=postgresql.JSON(astext_type=sa.Text()),
                                  nullable=False)
            batch_op.alter_column('model_id',
                                  existing_type=sa.VARCHAR(length=255),
                                  nullable=False)
            batch_op.alter_column('provider',
                                  existing_type=sa.VARCHAR(length=255),
                                  nullable=False)
    else:
        op.execute("ALTER TABLE app_model_configs MODIFY provider VARCHAR(255) NOT NULL;")
        op.execute("ALTER TABLE app_model_configs MODIFY model_id VARCHAR(255) NOT NULL;")
        op.execute("ALTER TABLE app_model_configs MODIFY configs JSON NOT NULL;")

    # ### end Alembic commands ###
