"""add-tool-index

Revision ID: dfb3b7f477da
Revises: b24be59fbb04
Create Date: 2024-01-24 02:17:01.631635

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import models.types

# revision identifiers, used by Alembic.
revision = 'dfb3b7f477da'
down_revision = 'b24be59fbb04'
branch_labels = None
depends_on = None


def _is_pg(conn):
    return conn.dialect.name == "postgresql"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # 处理 tool_api_providers 唯一约束（MySQL 改用 CREATE UNIQUE INDEX）
    if _is_pg(conn):
        with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
            batch_op.create_unique_constraint(
                'unique_api_tool_provider',
                ['name', 'tenant_id']
            )
    else:
        # MySQL 兼容写法：CREATE UNIQUE INDEX 替代 ALTER TABLE ADD CONSTRAINT
        op.execute("CREATE UNIQUE INDEX unique_api_tool_provider ON tool_api_providers (name, tenant_id)")

    # 处理 tool_files 索引（无需修改）
    with op.batch_alter_table('tool_files', schema=None) as batch_op:
        batch_op.create_index('tool_file_conversation_id_idx', ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 tool_files 索引
    with op.batch_alter_table('tool_files', schema=None) as batch_op:
        batch_op.drop_index('tool_file_conversation_id_idx')

    # 兼容删除唯一约束/索引
    conn = op.get_bind()
    if _is_pg(conn):
        with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
            batch_op.drop_constraint('unique_api_tool_provider', type_='unique')
    else:
        # MySQL 删除唯一索引（约束名即索引名）
        op.execute("DROP INDEX unique_api_tool_provider ON tool_api_providers")

    # ### end Alembic commands ###
